title: Deburson
email: hello@deburson.com
description: Contract product management and consulting for platform products, APIs, and developer programs.
baseurl: ""
url: "https://deburson.github.io"

theme: minima

plugins:
  - jekyll-feed
